<?php

namespace Blog\FrontBundle\Repository;

/**
 * BiographyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BiographyRepository extends \Doctrine\ORM\EntityRepository
{
}
