<?php

namespace Blog\FrontBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * 
     * @param integer $nbPosts
     * @return Array Post
     */
    public function getLastPosts($nbPosts)
    {
        $request = 'SELECT p,u
            FROM BlogFrontBundle:Post p JOIN p.user u
            ORDER BY p.datePublish DESC';
        $query = $this->getEntityManager()->createQuery($request);
        $query->setFirstResult(0);
        $query->setMaxResults($nbPosts);
        return $query->getResult();
    }
}
